// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmujzylpveiqpkztkkxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtdWp6eWxwdmVpcXBrenRra3h4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzOTg5MTMsImV4cCI6MjA2NDk3NDkxM30.nCSHvCp0LRP_v5Rcu0OVY-vDze4aSCK1fb5db4OnZCo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);